### ISSUE TITLE
Add background <circle> element, to allow inverted colors

### ISSUE THREAD

**Issue by Kikobeats** [iqnivek/react-circular-progressbar#21]
First of all, nice component!

I need to use it using a background color for the round, and a white or semi transparent line.

Because the component is drawing just the line, how to do that?

something like that: https://codepen.io/web-tiki/pen/qEGvMN

**Comment by iqnivek** [comment]
yea we'd need to add a new `<circle>` element in order to do that, which doesn't exist yet. Seems pretty reasonable to add.. I can look into it but PRs are welcome too.

**Comment by andreysaleba** [comment]
Hey, I've submitted PR with the <circle> inside of <svg>. Can you check it - https://github.com/iqnivek/react-circular-progressbar/pull/23?

**Comment by iqnivek** [comment]
This is now available in v0.4.0! Example usage:

JSX:

```
<CircularProgressbar
  className="inverted"
  background
  percentage={66}
/>
```

CSS:

```css
.CircularProgressbar.inverted .CircularProgressbar-background {
  fill: #3e98c7;
}

.CircularProgressbar.inverted .CircularProgressbar-text {
  fill: #fff;
}

.CircularProgressbar.inverted .CircularProgressbar-path {
  stroke: #fff;
}

.CircularProgressbar.inverted .CircularProgressbar-trail {
  stroke: transparent;
}
```

You can also use a `backgroundPadding` prop to control the spacing between the background edge and the progressbar.

Thanks @Kikobeats for the idea and @andreysaleba for contributing the original PR!
