### ISSUE TITLE
Not working in flexboxes

### ISSUE THREAD

**Issue by sofianegargouri** [iqnivek/react-circular-progressbar#5]
It looks like the component is not working when placed in a div with `display: flex`

**Comment by iqnivek** [comment]
good catch. I think this is because elements inside a flex container have no intrinsic width when you don't specify width, unlike divs where the component will expand to the width of the container.

One fix for this is to specify an explicit width on the component:

```css
.CircularProgressbar {
  width: 100%;  // or flex: 1 or 200px, whatever you want
}
```

Not sure yet, but I may add `width: 100%` to styles.css. I wanted to keep width unspecified, but since that stylesheet can be configured anyway, it might be the right choice.

Thanks for the feedback!
