### ISSUE TITLE
Time for the animation

### ISSUE THREAD

**Issue by krit-gpt** [iqnivek/react-circular-progressbar#54]
Hi, 
I wanted to know if there was any way of changing the time of the animation, example from 0% to 80% and make it faster or slower.
I tried changing

```javascript
ChangingProgressbar.defaultProps = {
  interval: 1000
};
```
the value of the interval variable, but it does not have any effect on the duration of the animation.
Thanks!

**Comment by iqnivek** [comment]
Hey @krit-gpt!

Good question - I didn't make this super clear in the documentation. Animation speed is controlled by the CSS transition property on the SVG path element.

In your CSS file, you'll want to customize

```css
.CircularProgressbar-path {
  transition: stroke-dashoffset 1s ease 0s;  // replace "1s" with your desired animation duration
}
```

See a working example here which shows progressbars with two different animation speeds: https://codesandbox.io/s/x29rxrr4kw

Hope this helps!
